USB_VID = 0x4567
USB_PID = 0x0001

USB_PRODUCT = "ESP32S3-B-N16R8"
USB_MANUFACTURER = "WeAct"

IDF_TARGET = esp32s3

UF2_BOOTLOADER = 0

CIRCUITPY_ESP_FLASH_SIZE = 16MB
CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 40m

CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 80m

CIRCUITPY_ESPCAMERA = 0

CONFIG_SPIRAM_CLK_IO = 30
CONFIG_SPIRAM_CS_IO = 26

# Include these Python libraries in firmware.
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_NeoPixel
